# Generated by Django 5.0.1 on 2024-02-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
