# Generated by Django 5.0.1 on 2024-02-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_course_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='SMS.student'),
        ),
    ]
