# Generated by Django 5.0.1 on 2024-02-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
